Repository GSG-FC02/To-Do-SA, pull requests merged in 2021-03, with the labels that each got.

#5 Add main page html file and style css file
  Todo-list.png
  main page.html
  style.css
Labels: in-progress

#7 readme
  README.md
Labels: Done

#8 add to do list page files
  to-do-list-page.css
  to-do-list-page.html
Labels: Done

#9 add js code
  index.html
  to-do-list-page.css
  to-do-list-page.js
Labels: awaiting-review

#11 change file structure
  assest/vector-creator (3).png
  html/to-do-list-page.html
  index.html
  js/to-do-list-page.js
  style/style.css
  style/to-do-list-page.css
Labels: Done

#13 make some changes tp the js file
  js/to-do-list-page.js
Labels: Done
